spring:
  profiles:
    active: 
    - dev

---
spring:
  profiles: dev
  application:
    name: microcloud-test-dev
  
---
spring:
  profiles: defalut
  application:
    name: microcloud-test-default
  